puts "Deleting book exchange data..."
Book.destroy_all
User.destroy_all
Dropbox.destroy_all
Review.destroy_all
Genre.destroy_all

puts "🌱 Seeding dropbox..."
park_slope = Dropbox.create!(dropbox_location: "253 Flatbush Ave, Brooklyn, NY 11217", zip: "11215")
crown_heights = Dropbox.create!(dropbox_location: "409 Lincoln Pl, Brooklyn, NY 11238", zip: "11238")

puts "🌱 Seeding reviews..."

puts "🌱 Seeding genres..."
classics = Genre.create!(genre: "Classics")
contemporary = Genre.create!(genre: "Contemporary Fiction")
scifi = Genre.create!(genre: "Dystopian and Science Fiction")
comic = Genre.create!(genre: "Graphic Novel and Comic Books")
mystery = Genre.create!(genre: "Mystery, Horror, and Thriller")
fantasy = Genre.create!(genre: "Fantasy and Literary Fiction")
historical = Genre.create!(genre: "Historical Fiction")
romance = Genre.create!(genre: "Romance")
memoir = Genre.create!(genre: "Memoir and Biography")
cookbooks = Genre.create!(genre: "Cookbooks")
selfhelp = Genre.create!(genre: "Self Help and Spirituality")
howto = Genre.create!(genre: "How To")
poetry = Genre.create!(genre: "Poetry, Essays, and Short Stories")
children = Genre.create!(genre: "Children and Young Adults")

puts "🌱 Seeding users..."
#name, neighborhood, dropbox_id, is_admin(True/False) -- not adding yet: :password_digest
micaela = User.create!(name: "Micaela Frank", username: "mfrank", tokens: 3, total_acquired_books: 4, zip: "11215", dropbox_id: park_slope.id, is_admin: true, password: "password")
akilah = User.create!(name: "Akilah Snowden", username: "asnowden", tokens: 3, total_acquired_books: 5, zip: "11215", dropbox_id: park_slope.id, is_admin: true, password: "password")
leigh = User.create!(name: "Leigh Ryffel", username: "lryffel", tokens: 3, password: "password", total_acquired_books: 2, zip: "11238", dropbox_id: crown_heights.id, is_admin: false)
norah = User.create!(name: "Norah Taylor", username: "ntaylor", tokens: 3, total_acquired_books: 1, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
james = User.create!(name: "James Ng", username: "jng", tokens: 3, total_acquired_books: 2, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
sinclair = User.create!(name: "Sinclair Shang", username: "sshang", tokens: 3, total_acquired_books: 5, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
nyinyi = User.create!(name: "NyiNyi Lay Htet", username: "nlayhtet", tokens: 3, total_acquired_books: 7, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
em = User.create!(name: "Em Kramm", username: "ekramm", tokens: 3, total_acquired_books: 6, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
mark = User.create!(name: "Mark Wilkins", username: "mwilkins", tokens: 3, total_acquired_books: 3, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
corey = User.create!(name: "Corey Schadeck", username: "cschadeck", tokens: 3, total_acquired_books: 1, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
osvaldo = User.create!(name: "Osvaldo X.", username: "osvaldox", tokens: 3, total_acquired_books: 3, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
tashi = User.create!(name: "Tashi Dolma", username: "tdolma", tokens: 3, total_acquired_books: 4, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
robert = User.create!(name: "Robert Gittings", username: "rgittings", tokens: 3, total_acquired_books: 3, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
yeming = User.create!(name: "Yeming Luo", username: "yluo", tokens: 3, total_acquired_books: 8, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
peachy = User.create!(name: "Peachy Burnside", username: "pburnside", tokens: 3, total_acquired_books: 2, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
omar = User.create!(name: "Omar Tantawy", username: "otantawy", tokens: 3, total_acquired_books: 0, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
yixin = User.create!(name: "Yixin Gong", username: "ygong", tokens: 3, total_acquired_books: 1, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
yax = User.create!(name: "Yax Cruz Juarez", username: "ycruzjuarez", tokens: 3, total_acquired_books: 1, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
william = User.create!(name: "William Hwang", username: "whwang", tokens: 3, total_acquired_books: 0, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
ludwig = User.create!(name: "Ludwig Cadet", username: "lcadet", tokens: 3, total_acquired_books: 3, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
kenneth = User.create!(name: "Kenneth Mei", username: "kmei", tokens: 3, total_acquired_books: 2, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
jonathan = User.create!(name: "Jonathan Aguilar", username: "jaguilar", tokens: 3, total_acquired_books: 0, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
kaven = User.create!(name: "Kaven Kim", username: "kkim", tokens: 3, total_acquired_books: 2, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
mohammad = User.create!(name: "Mohammad Hossain", username: "mhossain", tokens: 3, total_acquired_books: 2, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
justin = User.create!(name: "Justin Muzzi", username: "jmuzzi", tokens: 3, total_acquired_books: 1, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
joshua = User.create!(name: "Joshua Tripe", username: "jtripe", tokens: 3, total_acquired_books: 0, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
jen = User.create!(name: "Jen Rosen", username: "jrosen", tokens: 3, total_acquired_books: 4, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
mark = User.create!(name: "Mark Stapf", username: "mstapf", tokens: 3, total_acquired_books: 3, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
marcus = User.create!(name: "Marcus Dertz", username: "mdertz", tokens: 3, total_acquired_books: 4, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
eli = User.create!(name: "Eli Ferrell", username: "eferrell", tokens: 3, total_acquired_books: 0, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
elle = User.create!(name: "Elle Barr", username: "ebarr", tokens: 3, total_acquired_books: 5, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
sophie = User.create!(name: "Sophie Canter", username: "scanter", tokens: 3, total_acquired_books: 1, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
brett = User.create!(name: "Brett Decker", username: "bdecker", tokens: 3, total_acquired_books: 3, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
james = User.create!(name: "James Cohen", username: "jcohen", tokens: 3, total_acquired_books: 3, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
duncan = User.create!(name: "Duncan Sharp", username: "dsharp", tokens: 3, total_acquired_books: 2, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
zoe = User.create!(name: "Zoe Wilson", username: "zwilson", tokens: 3, total_acquired_books: 2, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
aaron = User.create!(name: "Aaron Williamson", username: "awilliamson", tokens: 3, total_acquired_books: 2, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
aaron2 = User.create!(name: "Aaron Gross", username: "agross", tokens: 3, total_acquired_books: 2, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
everet = User.create!(name: "Everett Vixum", username: "evixium", tokens: 3, total_acquired_books: 2, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
priscilla = User.create!(name: "Priscilla Allouche", username: "pallouche", tokens: 3, total_acquired_books: 2, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
harley = User.create!(name: "Harley Samberg", username: "hsamberg", tokens: 3, total_acquired_books: 2, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
alana = User.create!(name: "Alana Hauser", username: "ahauser", tokens: 3, total_acquired_books: 5, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
micah = User.create!(name: "Micah Hauser", username: "mhauser", tokens: 3, total_acquired_books: 2, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
christopher = User.create!(name: "Christopher Hanson", username: "chanson", tokens: 3, total_acquired_books: 2, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
andy = User.create!(name: "Andy Brenwite", username: "abrenwite", tokens: 3, total_acquired_books: 1, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
evan = User.create!(name: "Evan Gittelson", username: "egittelson", tokens: 3, total_acquired_books: 1, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
brooke = User.create!(name: "Brooke Valera", username: "bvalera", tokens: 3, total_acquired_books: 3, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
steven = User.create!(name: "Steven Shaw", username: "sshaw", tokens: 3, total_acquired_books: 3, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
peter = User.create!(name: "Peter Lisnow", username: "plisnow", tokens: 3, total_acquired_books: 4, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
carly = User.create!(name: "Carly Linberg", username: "clinberg", tokens: 3, total_acquired_books: 1, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
lauren = User.create!(name: "Lauren Abrellio", username: "labrellio", tokens: 3, total_acquired_books: 2, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
juliet = User.create!(name: "Juliet Graffer", username: "jgraffer", tokens: 3, total_acquired_books: 1, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
rachel = User.create!(name: "Rachel Warren", username: "rwarren", tokens: 3, total_acquired_books: 3, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
angelica = User.create!(name: "Angelica Recchia", username: "arecchia", tokens: 3, total_acquired_books: 6, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
anabella = User.create!(name: "Anabella Benfare", username: "abenfare", tokens: 3, total_acquired_books: 1, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
sofia = User.create!(name: "Sofia Alvaniera", username: "salvaniera", tokens: 3, total_acquired_books: 2, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
benson = User.create!(name: "Benson Wollard", username: "bwollard", tokens: 3, total_acquired_books: 3, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
roxy = User.create!(name: "Roxy Kay", username: "rkay", tokens: 3, total_acquired_books: 2, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
becky = User.create!(name: "Becky Berg", username: "bberg", tokens: 3, total_acquired_books: 2, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
sam = User.create!(name: "Sam Rithe", username: "srithe", tokens: 3, total_acquired_books: 1, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
nate = User.create!(name: "Nate Donikoff", username: "ndonikoff", tokens: 3, total_acquired_books: 0, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
claire = User.create!(name: "Claire Gray", username: "cgray", tokens: 3, total_acquired_books: 0, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
jasper = User.create!(name: "Jasper Black", username: "jblack", tokens: 3, total_acquired_books: 0, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
andrew = User.create!(name: "Andrew Mason", username: "amason", tokens: 3, total_acquired_books: 1, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
benjamin = User.create!(name: "Benjamin Hoovia", username: "bhoovia", tokens: 3, total_acquired_books: 1, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
ariana = User.create!(name: "Ariana Prisinzano", username: "aprisinzano", tokens: 3, total_acquired_books: 3, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
frank = User.create!(name: "Frank Prisinzano", username: "fprisinzano", tokens: 3, total_acquired_books: 4, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
nick = User.create!(name: "Nick Viall", username: "nviall", tokens: 3, total_acquired_books: 2, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
catie = User.create!(name: "Catie Booth", username: "cbooth", tokens: 3, total_acquired_books: 5, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
jason = User.create!(name: "Jason Tartick", username: "jtartick", tokens: 3, total_acquired_books: 3, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
gabby = User.create!(name: "Gabby Windey", username: "gwindey", tokens: 3, total_acquired_books: 2, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
bri = User.create!(name: "Bri Springs", username: "bsprings", tokens: 3, total_acquired_books: 1, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
gabriela = User.create!(name: "Gabriela Cox", username: "gcox", tokens: 3, total_acquired_books: 0, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
casey = User.create!(name: "Casey Tamkin", username: "ctamkin", tokens: 3, total_acquired_books: 0, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
emilio = User.create!(name: "Emilio Parago", username: "eparago", tokens: 3, total_acquired_books: 0, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
milan = User.create!(name: "Milan Tessler", username: "mtessler", tokens: 3, total_acquired_books: 1, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
pepper = User.create!(name: "Pepper Anne", username: "panne", tokens: 3, total_acquired_books: 2, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
frank = User.create!(name: "Frank Weber", username: "fweber", tokens: 3, total_acquired_books: 1, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
eddie = User.create!(name: "Eddie Anderson", username: "eanderson", tokens: 3, total_acquired_books: 0, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
rosie = User.create!(name: "Rosie Randolph", username: "rrandolph", tokens: 3, total_acquired_books: 0, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
carl = User.create!(name: "Carl Krauss", username: "ckrauss", tokens: 3, total_acquired_books: 0, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
dan = User.create!(name: "Dan Tarlia", username: "dtarlia", tokens: 3, total_acquired_books: 1, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
lucia = User.create!(name: "Lucia Heller", username: "lheller", tokens: 3, total_acquired_books: 1, zip: "11215", dropbox_id: park_slope.id, is_admin: false, password: "password")
simon = User.create!(name: "Simon Lawrence", username: "slawrence", tokens: 3, total_acquired_books: 0, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
ted = User.create!(name: "Teddy Lewis", username: "tlewis", tokens: 3, total_acquired_books: 2, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
becca = User.create!(name: "Becca Kufrin", username: "bkufrin", tokens: 3, total_acquired_books: 4, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
thomas = User.create!(name: "Thomas Jacobs", username: "tjacobs", tokens: 3, total_acquired_books: 2, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")
tia = User.create!(name: "Tia Bristowe", username: "tbristowe", tokens: 3, total_acquired_books: 2, zip: "11238", dropbox_id: crown_heights.id, is_admin: false, password: "password")

puts "🌱 Seeding books..."

book1 = Book.create!(title: "Eloquent JavaScript", author: "Marijn Haverbeke", genre_id: howto.id, description: "A guide to Javascript that focuses on programming fundamentals and techniques. with clear examples and a focus on elegance, Eloquent JavaScript will have you fluent in the language of the web in no time.", user_id: osvaldo.id, can_claim: true) 

book2 = Book.create!(title: "Code: The Hidden Language Of Computer", author: "Charles Petzold", genre_id: howto.id, description: "Using everyday objects and familiar language systems such as Braille and Morse code, author Charles Petzold weaves an illuminating narrative for anyone who's ever wondered about the secret inner life of computers and other smart machines.", user_id: em.id, can_claim: true)

book3 = Book.create!(title: "Leave The World Behind", author: "Rumaan Alam", genre_id: scifi.id, description: "A magnetic novel about two families, strangers to each other, who are forced together on a long weekend gone terribly wrong.", user_id: yeming.id, can_claim: true) 

book4 = Book.create!(title: "Pure Colour", author: "Sheila Heiti", genre_id: fantasy.id, description: "Pure Colour seeks answers about love, Mortality and God. In Sheila Heti's new novel, a young woman considers the state of civilization and briefly joins her dead father on another plane of existence.", user_id: yixin.id, can_claim: true) 

book5 = Book.create!(title: "The Mothers", author: "Brit Bennett", genre_id: fantasy.id, description: "Set within a contemporary black community in Southern California, Brit Bennett's mesmerizing first novel is an emotionally perceptive story about community, love, and ambition. It begins with a secret.", user_id: brett.id, can_claim: true) 

book6 = Book.create!(title: "Night Bitch", author: "Rachel Yoder", genre_id: mystery.id, description: "An outrageously original novel of ideas about art, power and womanhood wrapped in a satirical fairy tale, Nightbitch will make you want to howl in laughter and recognition.", user_id: peachy.id, can_claim: true) 

book7 = Book.create!(title: "Crying In H Mart", author: "Michelle Zauner", genre_id: memoir.id, description: "An unflinching, powerful memoir about growing up Korean American, losing her mother, and forging her own identity. It was her mother's diagnosis of terminal pancreatic cancer, when Michelle was twenty-five, that forced a reckoning with her identity and brought her to reclaim the gifts of taste, language, and history her mother had given her.", user_id: sophie.id, can_claim: true) 

book8 = Book.create!(title: "November 9", author: "Colleen Hoover", genre_id: romance.id, description: "An unforgettable love story between a writer and his unexpected muse. Fallon meets Ben, an aspiring novelist, the day before her scheduled cross-country move. Can Ben's relationship with Fallon—and simultaneously his novel—be considered a love story if it ends in heartbreak?", user_id: william.id, can_claim: true) 

book9 = Book.create!(title: "It Ends With Us", author: "Colleen Hoover", genre_id: romance.id, description: "Sometimes the one who loves you is the one who hurts you the most. After Lily's move to Boston upon college graduation, she feels a spark with neurosurgeon Ryle Kincaid. As questions about her new relationship overwhelm her, so do thoughts of Atlas Corrigan – her first love and a link to the past she left behind. He was her kindred spirit, her protector. When Atlas suddenly reappears, everything Lily has built with Ryle is threatened.", user_id: james.id, can_claim: true) 

book10 = Book.create!(title: "You Too Can Have A Body Like Mine", author: "Alexandra Kleeman", genre_id: contemporary.id, description: "A wholly singular vision of contemporary womanhood from a terrifying and often funny voice of a new generation. A woman known only by the letter A lives in an unnamed American city with her roommate, B, and boyfriend, C, who wants her to join him on a reality show called That’s My Partner! A eats (or doesn’t) the right things, watches endless amounts of television, often just for the commercials—particularly the recurring cartoon escapades of Kandy Kat, the mascot for an entirely chemical dessert—and models herself on a standard of beauty that only exists in such advertising. Meanwhile B is attempting to make herself a twin of A, who hungers for something to give meaning to her life, something aside from C’s pornography addiction, and becomes indoctrinated by a new religion spread throughout a web of corporate franchises", user_id: leigh.id, can_claim: true)

book11 = Book.create!(title: "The Artists Way", author: "Julia Cameron", genre_id: selfhelp.id, description: "The Artist’s Way is the seminal book on the subject of creativity. An international bestseller, millions of readers have found it to be an invaluable guide to living the artist’s life. Still as vital today—or perhaps even more so—than it was when it was first published one decade ago, this book will help get you back on track, rediscover your passions, and take the steps you need to change your life.", user_id: nyinyi.id, can_claim: true)

book12 = Book.create!(title: "The Hill We Climb", author: "Amanda Gorman", genre_id: poetry.id, description: "Amanda Gorman’s remarkable new collection reveals an energizing and unforgettable voice in American poetry. Including “The Hill We Climb,” the stirring poem read at the inauguration of Joe Biden, and bursting with musical language and exploring themes of identity, grief, and memory; this lyric of hope and healing captures an important moment in our country’s consciousness while being utterly timeless.", user_id: priscilla.id, can_claim: true)

book13 = Book.new(title: "Cracking the Cube", author: "Ian Scheffler", genre_id: howto.id, user_id: micaela.id, can_claim: true, description: "In Cracking the Cube, Ian Scheffler reveals that cubing isn’t just fun and games. Along with participating in speedcubing competitions—from the World Championship to local tournaments—and interviewing key figures from the Cube’s history, he journeys to Budapest to seek a meeting with Rubik, who is still tinkering away with puzzles in his seventies. Getting sucked into the competitive circuit himself, Scheffler becomes engrossed in solving Rubik’s Cube in under twenty seconds, and the difference between the best and everyone else.")

book14 = Book.new(title: "How To Solve A Rubiks Cube For Kids", author: "Charlotte Gibbs", genre_id: children.id, user_id: jonathan.id, can_claim: true, description: "Learning how to solve a Rubik's cube is not only fun but also develops multiple cognitive and emotional skills that will benefit your child throughout their entire life: improving memory, developing patience, and encouraging critical thinking. Your child will meet Rubik's Cube, a cute cube who woke up with his colors mixed up! The Rubik's Cube character breaks down the process into sections such as Solving the Daisy or Solving the Yellow Cross.")

book15 = Book.new(title: "With Teeth", author: "Kristen Arnett", genre_id: contemporary.id, user_id: norah.id, can_claim: true, description: "If she's being honest, Sammie Lucas is scared of her son. Working from home in the close quarters of their Florida house, she lives with one wary eye peeled on Samson, a sullen, unknowable boy who resists her every attempt to bond with him. Uncertain in her own feelings about motherhood, Sammie grows increasingly resentful of Monika, her confident but absent wife. As Samson grows from feral toddler to surly teenager, Sammie's life begins to deteriorate into a mess of unruly behavior, and her struggle to create! a picture-perfect queer family unravels. When her son's hostility finally spills over into physical aggression, Sammie must confront her role in the mess--and the possibility that it will never be clean again.")

book16 = Book.new(title: "Slaughterhouse-Five", author: "Kurt Vonnegut", description: "Slaughterhouse-Five, an American classic, is one of the world’s great antiwar books. Centering on the infamous firebombing of Dresden, Billy Pilgrim’s odyssey through time reflects the mythic journey of our own fractured lives as we search for meaning in what we fear most.", genre_id: scifi.id, user_id: mark.id, can_claim: true)

book17 = Book.new(title: "The Year of Magical Thinking", author: "Joan Didion", genre_id: memoir.id, can_claim: true, user_id: james.id, description: "This book is Joan Didion’s account of the year following the death of her husband, writer John Gregory Dunne, and her attempts to make sense of her grief while tending to the severe illness of her adopted daughter, Quintana. As she tries to make sense of John’s death and her own changed identity, Didion discovers that grief is not what she expected it to be.")

book18 = Book.create!(title: "The Alchemist", author: "Paul Coelho", genre_id: selfhelp.id, can_claim: true, user_id: osvaldo.id, description: "Paulo Coelho's masterpiece tells the magical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure as extravagant as any ever found. The story of the treasures Santiago finds along the way teaches us, as only a few stories can, about the essential wisdom of listening to our hearts, learning to read the omens strewn along life's path, and, above all, following our dreams.")

book19 = Book.create!(title: "Daring Greatly", author: "Brene Brown", genre_id: selfhelp.id, can_claim: true, user_id: akilah.id, description: "Daring Greatly is not about winning or losing. It’s about courage and letting ourselves be seen. In a world where “never enough” dominates and feeling afraid has become second nature, vulnerability is subversive and even a little dangerous at times. And, without question, putting ourselves out there means there’s a far greater risk of getting criticized or feeling hurt. But when we step back and examine our lives, we will find that nothing is as uncomfortable, dangerous, and hurtful as standing on the outside of our lives looking in and wondering what it would be like if we had the courage to step into the. Daring Greatly is a practice and a powerful new vision for letting ourselves be seen.")

book20 = Book.create!(title: "The Outliers", author: "Malcolm Gladwell", genre_id: selfhelp.id, can_claim: true, user_id: yax.id, description: "In this stunning book, Malcolm Gladwell asks the question: what makes high-achievers different? His answer is that we pay too much attention to what successful people are like, and too little attention to where they are from: that is, their culture, their family, their generation, and the idiosyncratic experiences of their upbringing. Along the way he explains the secrets of software billionaires, what it takes to be a great soccer player, and what made the Beatles the greatest rock band.")

book21 = Book.create!(title: "Think And Grow Rich", author: "Napoleon Hill", genre_id: selfhelp.id, can_claim: true, user_id: sinclair.id, description: "Think And Grow Rich is the bible for successful people in general. It’ll also make you rich, but not necessarily by picking stocks. Here are the 3 that will get you the furthest: Use autosuggestion to build an unshakable belief in yourself, Be stubborn and always stick to your decisions, and Join a Mastermind group to cut the learning curve.")

book22 = Book.create!(title: "Artisan Sourdough Made Simple", author: "Emilie Raffa", genre_id: cookbooks.id, can_claim: true, user_id: robert.id, description: "Many bakers speak of their sourdough starter as if it has a magical life of its own, so it can be intimidating to those new to the sourdough world; fortunately with Artisan Sourdough Made Simple, Emilie Raffa removes the fear and proves that baking with sourdough is easy, and can fit into even a working parent’s schedule! Any new baker is inevitably hit with question after question. Emilie has the answers. As a professionally trained chef and avid home baker, she uses her experience to guide readers through the science and art of sourdough.")

book23 = Book.create!(title: "Just Like Mother", author: "Anne Heltzer", genre_id: mystery.id, can_claim: true, user_id: corey.id, description: "The last time Maeve saw her cousin was the night she escaped the cult they were raised in. For the past two decades, Maeve has worked hard to build a normal life in New York City, where she keeps everything―and everyone―at a safe distance. When Andrea suddenly reappears, Maeve regains the only true friend she’s ever had. The more Maeve immerses herself in Andrea’s world, the more disconnected she feels from her life back in the city; and the cousins’ increasing attachment triggers memories Maeve has fought hard to bury. But confronting the terrors of her childhood may be the only way for Maeve to transcend the nightmare still to come...")

book24 = Book.create!(title: "Chess Fundamentals", author: "Jose Raul Capablanca", genre_id: howto.id, can_claim: true, user_id: omar.id, description: "Play to Win! Jose Raul Capablanca was one of the greatest World Chess Champions of all time! While his playing style was straightforward he played with a blazing speed and strength that had never been seen before or since. In Chess Fundamentals Capablanca gives the reader a glimpse into his thinking patterns and strategy. Perfect for any playing level. The advice and exercises herein will make anyone and everyone a stronger player.") 

book25 = Book.create!(title: "Maus", author: "Art Spiegelman", genre_id: comic.id, can_claim: true, user_id: yeming.id, description: "A brutally moving work of art—widely hailed as the greatest graphic novel ever written—Maus recounts the chilling experiences of the author’s father during the Holocaust, with Jews drawn as wide-eyed mice and Nazis as menacing cats. Maus is a haunting tale within a tale, weaving the author’s account of his tortured relationship with his aging father into an astonishing retelling of one of history's most unspeakable tragedies. It is an unforgettable story of survival and a disarming look at the legacy of trauma.")

book26 = Book.create!(title: "Eating Animals", author: "Jonathan Safran Foer", genre_id: selfhelp.id, can_claim: true, user_id: ludwig.id, description: "Eating Animals provides a dense discussion of what it means to eat animals in an industrialized world. It was written in close collaboration with Farm Forward, a US nonprofit organization promoting veganism and sustainable agriculture. As the title suggests, the particular phenomenon Foer focuses on is the consumption of meat. He discusses what eating meat has meant in the past, and what it means today. In doing so, he does not, as one might expect, make the claim that eating meat is intrinsically bad. Rather, he claims that eating meat is circumstantially bad; for example, it is bad when it entails the suffering of animals, environmental destruction, and/or a risk for human health.")

book27 = Book.create!(title: "Persepolis", author: "Marjane Satrapi", genre_id: comic.id, can_claim: true, user_id: kaven.id, description: "Wise, funny, and heartbreaking, Persepolis is Marjane Satrapi’s best-selling graphic memoir of growing up in Iran during the Islamic Revolution. In powerful black-and-white comic strip images, Satrapi tells the story of her life in Tehran from ages six to fourteen, years that saw the overthrow of the Shah’s regime, the triumph of the Islamic Revolution, and the devastating effects of war with Iraq. The intelligent and outspoken only child of committed Marxists and the great-granddaughter of one of Iran’s last emperors, Marjane bears witness to a childhood uniquely entwined with the history of her country.")

book28 = Book.create!(title: "Crime and Punishment", author: "Fyodor Dostoevsky", genre_id: classics.id, user_id: kenneth.id, can_claim: true, description: "Crime and Punishment follows the mental anguish and moral dilemmas of Rodion Raskolnikov, an impoverished ex-student in Saint Petersburg who plans to kill an unscrupulous pawnbroker, an old woman who stores money and valuable objects in her flat. He theorises that with the money he could liberate himself from poverty and go on to perform great deeds, and seeks to convince himself that certain crimes are justifiable if they are committed in order to remove obstacles to the higher goals of 'extraordinary' men. Once the deed is done, however, he finds himself racked with confusion, paranoia, and disgust. His theoretical justifications lose all their power as he struggles with guilt and horror and confronts both the internal and external consequences of his deed.")

book29 = Book.create!(title: "Dante's Inferno", author: "Dante Alighieri", genre_id: classics.id, user_id: yixin.id, can_claim: true, description: "Dante's Inferno, widely hailed as one of the great classics of Western literature, details Dante's journey through the nine circles of Hell. The voyage begins during Easter week in the year 1300, the descent through Hell starting on Good Friday. After meeting his guide, the eminent Roman poet Virgil, in a mythical dark wood, the two poets begin their descent through a baleful world of doleful shades, horrifying tortures, and unending lamentation.")

book30 = Book.create!(title: "Salt, Fat, Acid, Heat", author: "Samin Nosrat", genre_id: cookbooks.id, can_claim: true, user_id: leigh.id, description: "Salt, Fat Acid, Heat immediately bridges the gap between home and professional kitchens. With charming narrative, illustrated walkthroughs, and a lighthearted approach to kitchen science, Samin demystifies the four elements of good cooking for everyone. Refer to the canon of 100 essential recipes—and dozens of variations—to put the lessons into practice and make bright, balanced vinaigrettes, perfectly caramelized roast vegetables, tender braised meats, and light, flaky pastry doughs.")

book31 = Book.create!(title: "Nothing Fancy", author: "Alison Roman", genre_id: cookbooks.id, can_claim: true, user_id: william.id, description: "This abundant collection of all-new recipes is for gatherings big and small, any day of the week. Alison Roman will give you the food your people want (think DIY martini bar, platters of tomatoes, pots of coconut-braised chicken and chickpeas, pans of lemony turmeric tea cake) plus the tips, sass, and confidence to pull it all off. With Nothing Fancy, any night of the week is worth celebrating.")

book32 = Book.create!(title: "How To Win The Bachelor: The Secret to Finding Love and Fame on America's Favorite Reality Show", author: "Lizzy Pace & Chad Kultgen", genre_id: howto.id, can_claim: true, user_id: micaela.id, description: "Since its premiere in 2002, ABC’s The Bachelor has become a staple of American television. Now, discover the fascinating history of the show, uncover the ins and outs of the phenomenon that has become Bachelor Nation, and take a deeper look at what separates the winners from the losers. From how best to exit the limo on Night One, to strategies for making a run for the all-important First Impression Rose, to how to avoid being labeled a villain, this clear-eyed guide illustrates the rules and strategies any would-be contestant should know. The ultimate must-read for every fan, How to Win the Bachelor gives you an inside look at the franchise where The Rose holds all the power.")

book33 = Book.create!(title: "JavaScript For Kids: A Playful Introduction to Programming", author: "Nick Morgan", genre_id: children.id, can_claim: true, user_id: mark.id, description: "JavaScript is the programming language of the Internet, the secret sauce that makes the Web awesome, your favorite sites interactive, and online games fun! JavaScript for Kids is a lighthearted introduction that teaches programming essentials through patient, step-by-step examples paired with funny illustrations. You’ll begin with the basics, like working with strings, arrays, and loops, and then move on to more advanced topics, like building interactivity with jQuery and drawing graphics with Canvas.")

book34 = Book.create!(title: "Letters To A Young Poet", author: "Rainer Maria Rilke", genre_id: poetry.id, can_claim: true,user_id: james.id, description: "From 1903 to 1908 Rilke wrote a series of remarkable responses to a young, would-be poet on poetry and on surviving as a sensitive observer in a harsh world. Those letters, still a fresh source of inspiration and insight, are accompanied here by a chronicle of Rilke's life that shows what he was experiencing in his own relationship to life and work when he wrote them.")

book35 = Book.create!(title: "Baby Loves Coding!", author: "Irene Chan", genre_id: children.id, can_claim: true, user_id: james.id, description: "Accurate enough to satisfy an expert, yet simple enough for baby, this clever board book showcases the use of logic, sequence, and patterns to solve problems. Can Baby think like a coder to fix her train? Beautiful, visually stimulating illustrations complement age-appropriate language to encourage baby's sense of wonder. Parents and caregivers may learn a thing or two, as well!")

book36 = Book.create!(title: "Their Eyes Were Watching God", author: "Zora Neale Hurston", genre_id: classics.id, can_claim: true, user_id: tashi.id, description: "One of the most important and enduring books of the twentieth century, Their Eyes Were Watching God brings to life a Southern love story with the wit and pathos found only in the writing of Zora Neale Hurston. Out of print for almost thirty years—due largely to initial audiences’ rejection of its strong black female protagonist—Hurston’s classic has since its 1978 reissue become perhaps the most widely read and highly acclaimed novel in the canon of African-American literature, and explores main character Janie Crawford's ripening from a vibrant, but voiceless, teenage girl into a woman with her finger on the trigger of her own destiny.")

book37 = Book.create!(title: "Such A Fun Age", author: "Kiley Reid", genre_id: contemporary.id, can_claim: true, user_id: sinclair.id, description: "A striking and surprising debut novel from an exhilarating new voice, Such a Fun Age is a page-turning and big-hearted story about race and privilege, set around a young black babysitter, her well-intentioned employer, and a surprising connection that threatens to undo them both. With empathy and piercing social commentary, this book explores the stickiness of transactional relationships, what it means to make someone family, and the complicated reality of being a grown up.")

book38 = Book.create!(title: "Strega Nona", author: "Tomie de Paola", genre_id: children.id, description: "Strega Nona—“Grandma Witch”—is the source for potions, cures, magic, and comfort in her Calabrian town. Her magical ever-full pasta pot is especially intriguing to hungry Big Anthony. Big Anthony is supposed to look after her house and tend her garden, but one day, when she goes over the mountain to visit Strega Amelia, he recites the magic verse over the pasta pot, with disastrous results.", user_id: yeming.id, can_claim: true)

book39 = Book.create!(title: "The Underground Railroad", author: "Colson Whitehead", genre_id: children.id, description: "Cora is a slave on a cotton plantation in Georgia. Life is hell for all the slaves, but especially bad for Cora; an outcast even among her fellow Africans, she is coming into womanhood—where even greater pain awaits. When Caesar, a recent arrival from Virginia, tells her about the Underground Railroad, they decide to take a terrifying risk and escape. Cora encounters different worlds at each stage of her journey—hers is an odyssey through time as well as space. The Underground Railroad is at once a kinetic adventure tale of one woman’s ferocious will to escape the horrors of bondage and a shattering, powerful meditation on the history we all share.", user_id: corey.id, can_claim: true)

book40 = Book.create!(title: "The Pillars of the Earth", author: "Colson Whitehead", genre_id: historical.id, user_id: nyinyi.id, can_claim: true, description: "A spellbinding epic set in 12th-century England, The Pillars of the Earth tells the story of the struggle to build the greatest Gothic cathedral the world has known—a struggle between good and evil that will turn church against state, and brother against brother.")

book41 = Book.create!(title: "People We Meet on Vacation", author: "Emily Henry", genre_id: romance.id, user_id: peachy.id, can_claim: true, description: "Poppy and Alex. Alex and Poppy. They have nothing in common. She’s a wild child; he wears khakis. She has insatiable wanderlust; he prefers to stay home with a book. And somehow, ever since a fateful car share home from college many years ago, they are the very best of friends. For most of the year they live far apart—she’s in New York City, and he’s in their small hometown—but every summer, for a decade, they have taken one glorious week of vacation together. Until two years ago, when they ruined everything. They haven’t spoken since. Now she has a week to fix everything. If only she can get around the one big truth that has always stood quietly in the middle of their seemingly perfect relationship. What could possibly go wrong?")

book42 = Book.create!(title: "The Catcher in the Rye", author: "J.D. Salinger", genre_id: children.id, user_id: robert.id, can_claim: true, description: "The Catcher in the Rye, novel by J.D. Salinger published in 1951. The novel details two days in the life of 16-year-old Holden Caulfield after he has been expelled from prep school. Confused and disillusioned, Holden searches for truth and rails against the “phoniness” of the adult world. It was originally intended for adults, but is often read by adolescents for its themes of angst, alienation, and as a critique of superficiality in society.")

book43 = Book.create!(title: "All The Light We Cannot See", author: "Anthony Doerr", genre_id: historical.id, user_id: ludwig.id, can_claim: true, description: "Ten years in the writing, Anthony Doerr's All the Light We Cannot See is an epic work of historical fiction. With richly detailed language and characters who are both brave and heartbreaking, Doerr weaves together the stories of a French girl named Marie-Laure who has lost her eyesight and a German orphan named Werner.")

book44 = Book.create!(title: "Parable of the Sower", author: "Octavia Butler", genre_id: scifi.id, user_id: micaela.id, can_claim: true, description: "When global climate change and economic crises lead to social chaos in the early 2020s, California becomes full of dangers, from pervasive water shortage to masses of vagabonds who will do anything to live to see another day. Fifteen-year-old Lauren Olamina lives inside a gated community with her preacher father, family, and neighbors, sheltered from the surrounding anarchy. In a society where any vulnerability is a risk, she suffers from hyperempathy, a debilitating sensitivity to others' emotions. Precocious and clear-eyed, Lauren must make her voice heard in order to protect her loved ones from the imminent disasters her small community stubbornly ignores. But what begins as a fight for survival soon leads to something much more: the birth of a new faith... and a startling vision of human destiny.")

book45 = Book.create!(title: "Parable of the Talents", author: "Octavia Butler", genre_id: scifi.id, user_id: kenneth.id, can_claim: true, description: "Lauren Olamina's love is divided among her young daughter, her community, and the revelation that led Lauren to found a new faith that teaches God Is Change. But in the wake of environmental and economic chaos, the U.S. government turns a blind eye to violent bigots who consider the mere existence of a black female leader a threat. And soon Lauren must either sacrifice her child and her followers -- or forsake the religion that can transform human destiny.")

book46 = Book.create!(title: "Time Is A Mother", author: "Ocean Vuong", genre_id: poetry.id, user_id: tashi.id, can_claim: true, description: "In this deeply intimate second poetry collection, Ocean Vuong searches for life among the aftershocks of his mother's death, embodying the paradox of sitting within grief while being determined to survive beyond it. Shifting through memory, and in concert with the themes of his novel On Earth We're Briefly Gorgeous, Vuong contends with personal loss, the meaning of family, and the cost of being the product of an American war in America. At once vivid, brave, and propulsive, Vuong's poems circle fragmented lives to find both restoration as well as the epicenter of the break.")

book47 = Book.create!(title: "Trick Mirror", author: "Jia Tolentino", genre_id: contemporary.id, user_id: norah.id, can_claim: true, description: "Trick Mirror is an enlightening, unforgettable trip through the river of self-delusion that surges just beneath the surface of our lives. This is a book about the incentives that shape us, and about how hard it is to see ourselves clearly through a culture that revolves around the self. In each essay, Tolentino writes about a cultural prism: the rise of the nightmare social internet; the advent of scamming as the definitive millennial ethos; the literary heroine’s journey from brave to blank to bitter; the punitive dream of optimization, which insists that everything, including our bodies, should become more efficient and beautiful until we die. Gleaming with Tolentino’s sense of humor and capacity to elucidate the impossibly complex in an instant, and marked by her desire to treat the reader with profound honesty, Trick Mirror is an instant classic of the worst decade yet.")

book48 = Book.create!(title: "Cook This Book", author: "Molly Baz", genre_id: cookbooks.id, user_id: yax.id, can_claim: true, description: "More than a collection of recipes, Cook This Book teaches you the invaluable superpower of improvisation though visually compelling lessons on such topics as the importance of salt and how to balance flavor, giving you all the tools necessary to make food taste great every time.")

book49 = Book.create!(title: "Milk Fed", author: "Melissa Broder", genre_id: contemporary.id, user_id: em.id, can_claim: true, description: "Rachel is twenty-four, a lapsed Jew who has made calorie restriction her religion. By day, she maintains an illusion of existential control, by way of obsessive food rituals, while working as an underling at a Los Angeles talent management agency. At night, she pedals nowhere on the elliptical machine. Rachel is content to carry on subsisting—until her therapist encourages her to take a ninety-day communication detox from her mother, who raised her in the tradition of calorie counting. Pairing superlative emotional insight with unabashed vivid fantasy, Broder tells a tale of appetites: physical hunger, sexual desire, spiritual longing, and the ways that we as humans can compartmentalize these so often interdependent instincts.")

book50 = Book.create!(title: "You Exist Too Much", author: "Zaina Arafat", genre_id: poetry.id, user_id: mark.id, can_claim: true, description: "You Exist Too Much is about wanting and not having. Arafat tries to do a lot in this novel, and she pulls it off. This is a story about a woman trapped in the interstitial space between different cultures and religions, but it's also about sexual identity and the effects of fear of rejection and codependency.")

book51 = Book.create!(title: "1984", author: "George Orwell", genre_id: classics.id, user_id: yeming.id, can_claim: true, description: "1984 is a dystopian novella by George Orwell published in 1949, which follows the life of Winston Smith, a low ranking member of 'the Party', who is frustrated by the omnipresent eyes of the party, and its ominous ruler Big Brother. 'Big Brother' controls every aspect of people's lives.")

book52 = Book.create!(title: "The Candy House", author: "Jennifer Egan", genre_id: fantasy.id, user_id: akilah.id, can_claim: true, description: "The Candy House opens with the staggeringly brilliant Bix Bouton, whose company, Mandala, is so successful that he is “one of those tech demi-gods with whom we’re all on a first name basis.” Bix is forty, with four kids, restless, and desperate for a new idea, when he stumbles into a conversation group, mostly Columbia professors, one of whom is experimenting with downloading or “externalizing” memory. Within a decade, Bix’s new technology, “Own Your Unconscious”—which allows you access to every memory you’ve ever had, and to share your memories in exchange for access to the memories of others—has seduced multitudes. In the world of Egan’s spectacular imagination, there are “counters” who track and exploit desires and there are “eluders,” those who understand the price of taking a bite of the Candy House. Egan introduces these characters in an astonishing array of narrative styles—from omniscient to first person plural to a duet of voices, an epistolary chapter, and a chapter of tweets. Intellectually dazzling, The Candy House is also a moving testament to the tenacity and transcendence of human longing for connection, family, privacy, and love.")

book53 = Book.create!(title: "A Little Life", author: "Hanya Yanagihara", genre_id: fantasy.id, user_id: mohammad.id, can_claim: true, description: "When four classmates from a small Massachusetts college move to New York to make their way, they're broke, adrift, and buoyed only by their friendship and ambition. There is kind, handsome Willem, an aspiring actor; JB, a quick-witted, sometimes cruel Brooklyn-born painter seeking entry to the art world; Malcolm, a frustrated architect at a prominent firm; and withdrawn, brilliant, enigmatic Jude, who serves as their center of gravity. Over the decades, their relationships deepen and darken, tinged by addiction, success, and pride. Yet their greatest challenge, each comes to realize, is Jude himself, by midlife a terrifyingly talented litigator yet an increasingly broken man, his mind and body scarred by an unspeakable childhood, and haunted by what he fears is a degree of trauma that he’ll not only be unable to overcome—but that will define his life forever.")

book54 = Book.create!(title: "One Hundred Years of Solitude", author: "Gabriel Garcia Marquez", genre_id: fantasy.id, user_id: omar.id, can_claim: true, description: "One Hundred Years of Solitude tells the story of the rise and fall, birth and death of the mythical town of Macondo through the history of the Buendiá family. Inventive, amusing, magnetic, sad and alive with unforgettable men and women—brimming with truth, compassion, and a lyrical magic that strikes the soul—this novel is a masterpiece in the art of fiction.")

book55 = Book.create!(title: "Beloved", author: "Toni Morrison", genre_id: historical.id, user_id: justin.id, can_claim: true, description: "Sethe was born a slave and escaped to Ohio, but eighteen years later she is still not free. She has borne the unthinkable and not gone mad, yet she is still held captive by memories of Sweet Home, the beautiful farm where so many hideous things happened. Meanwhile Sethe’s house has long been troubled by the angry, destructive ghost of her baby, who died nameless and whose tombstone is engraved with a single word: Beloved. Sethe works at beating back the past, but it makes itself heard and felt incessantly in her memory and in the lives of those around her. When a mysterious teenage girl arrives, calling herself Beloved, Sethe’s terrible secret explodes into the present. Combining the visionary power of legend with the unassailable truth of history, Morrison’s unforgettable novel is one of the great and enduring works of American literature.")

book56 = Book.create!(title: "Sula", author: "Toni Morrison", genre_id: historical.id, user_id: mohammad.id, can_claim: true, description: "This rich and moving novel traces the lives of two black heroines from their close-knit childhood in a small Ohio town, through their sharply divergent paths of womanhood, to their ultimate confrontation and reconciliation. Nel Wright has chosen to stay in the place where she was born, to marry, raise a family, and become a pillar of the black community. Sula Peace has rejected the life Nel has embraced, escaping to college, and submerging herself in city life. When she returns to her roots, it is as a rebel and a wanton seductress. Eventually, both women must face the consequences of their choices. Together, they create! an unforgettable portrait of what it means and costs to be a black woman in America.")

book57 = Book.create!(title: "The Life-Changing Magic of Tidying Up", author: "Marie Kondo", genre_id: howto.id, user_id: corey.id, can_claim: true, description: "Japanese cleaning consultant Marie Kondo takes tidying to a whole new level, promising that if you properly simplify and organize your home once, you'll never have to do it again. Most methods advocate a room-by-room or little-by-little approach, which doom you to pick away at your piles of stuff forever. With detailed guidance for determining which items in your house spark joy (and which don't), this international best seller featuring Tokyo's newest lifestyle phenomenon will help you clear your clutter and enjoy the unique magic of a tidy home - and the calm, motivated mindset it can inspire.")

book58 = Book.create!(title: "The Rumi Collection", author: "Rumi", genre_id: poetry.id, user_id: osvaldo.id, can_claim: true, description: "Arranged by topic and theme, this introduction to the works of the great mystical poet Rumi features some of the best translations of his verse. Rumi’s poems are beloved for their touching perceptions of humanity and the Divine. Here is a rich introduction to the work of the great mystical poet, featuring leading literary translations of his verse. Translators include Coleman Barks, Robert Bly, Andrew Harvey, Kabir Helminski, Camille Helminski, Daniel Liebert, and Peter Lamborn Wilson.")

book59 = Book.create!(title: "Reminders Of Him", author: "Colleen Hoover", genre_id: romance.id, description: "After serving five years in prison for a tragic mistake, Kenna Rowan returns to the town where it all went wrong, hoping to reunite with her four-year-old daughter. Kenna must find a way to absolve the mistakes of her past in order to build a future out of hope and healing.", user_id: aaron.id, can_claim: true)